### ISSUE TITLE
GitHub Repository

### ISSUE THREAD

**Issue by Ron31** [rednit-team/tinder.py#1]
- [ ] Plan out Readme
   - [ ] "Code Structure"
   - [ ] How to use?
   - [x] git-badges?
   - [ ] contributers Bot?
   - [ ] ??
- [ ] Templates
   - [x] Issue
   - [ ] PR
- [ ] dev branch

**Comment by anantdark** [comment]
Hey, i would love to contribute to your project, do let me know if you are interested.
